In [ ]:


'''  

Are subsets views or copies in Pandas?

Answer:

There is NO guarantee that loc or iloc always returns a view or always returns a copy.

• loc → May return a view or a copy depending on the operation.
• iloc → May also return a view or a copy depending on the operation.

Boolean indexing (filtering) almost always returns a copy.

Example:
df.loc[df["Age"] > 30]      # Returns a copy
df.iloc[0:5]                # May return a view or a copy
df.loc["A":"C"]             # May return a view or a copy

'''
#

# Are Subsets Views or Copies in Pandas?

In pandas, whether you get a view (linked to original DataFrame) or a copy (independent) 
depends on how you slice or filter — and it’s not always obvious.

- .iloc always returns a copy (safe, independent subset.)
- .loc may return a view (especially if indexing on labels)
    ```bash
    subset = df.loc[df['Sex'] == 'male']
    This is like the earlier filtering — might be a view.

    so..
    subset = df.loc[df['Sex'] == 'male'].copy()

    ```

| Situation                          | View or Copy? | Should you use `.copy()`? |
| ---------------------------------- | ------------- | ------------------------- |
| `.iloc[]` slicing                  | Mostly Copy   | Optional                  |
| `.loc[]` slicing                   | May be View   | Recommended               |
| Filtering with condition `df[...]` | May be View   | Recommended               |
| You plan to modify the subset      | Use `.copy()` | YES                       |

In [ ]:
import pandas as pd
titanic_dataset_local_url = "titanic.csv"
df = pd.read_csv(titanic_dataset_local_url)

df.head(5)
##print(df.head(5))
# passenger ID as Index

df_passenger_id_indexed = df.set_index("PassengerId")

df_passenger_id_indexed.head(5)

# Name as Index
df_name_indexed = df.set_index("Name")
df_name_indexed

df_name_indexed.loc["Braund, Mr. Owen Harris"] # used loc since name is used as labels

PassengerId            1
Survived               0
Pclass                 3
Sex                 male
Age                 22.0
SibSp                  1
Parch                  0
Ticket         A/5 21171
Fare                7.25
Cabin                NaN
Embarked               S
Name: Braund, Mr. Owen Harris, dtype: object

In [ ]:
import pandas as pd
# instead of below

subset = df[df['Sex'] == 'male'] # this may or may not create the view or copy of the original dataframe. So, it is not safe to use this.
subset['Age'] = subset['Age'] + 1

# SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame

In [ ]:
import pandas as pd
# use this

subset = df[df['Sex'] == 'male'].copy() #Since this is more safer since we are not changing any thing from the view , we are creating the new copy and storing it inot the subset
subset['Age'] += 1

subset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,23.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,36.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,55.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,3.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,29.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,26.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,28.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,27.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,33.0,0,0,370376,7.7500,NaN,Q

# Set Index vs Re - index

| Feature       | `set_index()`                               | `reindex()`                                          |
| ------------- | ------------------------------------------- | ---------------------------------------------------- |
| What it does  | **Moves a column** to become the index      | **Changes the row/column labels** of a DataFrame     |
| Main Use Case | Change the row labels using existing column | Match to new labels, add/remove/reorder rows/columns |
| Affects index | Yes – creates a **new index from a column** | Yes – but just **remaps or aligns to new index**     |
| Adds NaNs?    | No – only restructures                      | Yes – can insert NaNs for new labels                 |

# 1. set_index() — Use a column as the new index

In [ ]:

import pandas as pd
df_by_name = df.set_index('Name')
print(df_by_name.loc['Allen, Miss. Elisabeth Walton'])  # Now 'Name' is index

df_by_name.head()
# now to reset teh index we can use

df_by_name = df_by_name.reset_index()

PassengerId         731
Survived              1
Pclass                1
Sex              female
Age                29.0
SibSp                 0
Parch                 0
Ticket            24160
Fare           211.3375
Cabin                B5
Embarked              S
Name: Allen, Miss. Elisabeth Walton, dtype: object

# 2. reindex() — Conform to a new index/column structure

# For Rows

In [ ]:
import pandas as pd
sales_jan = pd.DataFrame({
    'Sales': [250, 400, 300]
}, index=['Store_A', 'Store_B', 'Store_C'])

sales_jan

print(sales_jan)

sales_feb = pd.DataFrame({
    'Sales': [260, 310]
}, index=['Store_A', 'Store_C'])

sales_feb

print(sales_feb)

# Here both the data frame we can see the index are different jan has Store_A, store_B, Store_c and feb has Store_A and Store_B

         Sales
Store_A    250
Store_B    400
Store_C    300
         Sales
Store_A    260
Store_C    310

❌ Problem: Indexes are mismatched!

You cannot safely do operations like subtraction or direct comparison unless indexes are aligned.

✅ 🛠 Solution: Use reindex() to align!

In [ ]:
import pandas as pd

# So to align the index of both dataframe we need to know the  which dataframe having full index full index , here we have jan with full indexes present of feb

common_index=sales_jan.index # gives indexes present in jan which is the common index present in 2 dataframe
print(common_index)

# now i want to reindex the dataframe of sales_feb on common index

sales_feb_aligned = sales_feb.reindex(common_index)

sales_feb_aligned # With NaN

'''  
	Sales
Store_A	260.0
Store_B	NaN
Store_C	310.0

'''
# We dont need nan bot zero we use fill_value=o as the parameter in re,index

sales_feb_aligned_with_zero = sales_feb.reindex(common_index, fill_value=0) # here it will directly affects the label and not the column to make the column align we have to explicitly use columns = dataframeName.columns

sales_feb_aligned_with_zero

#Now  jan and feb has the same indexes bow we can persornm the oprewation between both of them

sales_diff = sales_feb_aligned_with_zero['Sales'] - sales_jan['Sales']

sales_diff

Index(['Store_A', 'Store_B', 'Store_C'], dtype='str')

Store_A     10
Store_B   -400
Store_C     10
Name: Sales, dtype: int64

# For column

In [ ]:
import pandas as pd
source_a = pd.DataFrame({
    'Product': ['Laptop', 'Tablet', 'Phone'],
    'Price': [1000, 500, 800],
    'Stock': [30, 50, 100]
})
source_a

  Product  Price  Stock
0  Laptop   1000     30
1  Tablet    500     50
2   Phone    800    100

In [ ]:

import pandas as pd
source_b = pd.DataFrame({
    'Price': [980, 520, 810],
    'Product': ['Laptop', 'Tablet', 'Phone']
})

source_b

   Price Product
0    980  Laptop
1    520  Tablet
2    810   Phone

In [28]:
aligned_b = source_b.reindex(columns=source_a.columns, fill_value = 0)

aligned_b

  Product  Price  Stock
0  Laptop    980      0
1  Tablet    520      0
2   Phone    810      0

In [ ]:

import pandas as pd
stock_diff = source_a['Stock'] - aligned_b['Stock']

stock_diff

0     30
1     50
2    100
Name: Stock, dtype: int64

# Iteration in Pandas

In pandas, iteration refers to looping over rows or columns of a DataFrame or Series. While pandas is optimized for vectorized operations, sometimes we need to loop — for example, for conditional logic, debugging, or generating complex values.

In [2]:
import pandas as pd
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Delhi', 'Mumbai', 'Chennai']
})

print(df)

for index, row in df.iterrows():
    print(f"{index}: {row['Name']} lives in {row['City']} and is {row['Age']} years old.")

      Name  Age     City
0    Alice   25    Delhi
1      Bob   30   Mumbai
2  Charlie   35  Chennai
0: Alice lives in Delhi and is 25 years old.
1: Bob lives in Mumbai and is 30 years old.
2: Charlie lives in Chennai and is 35 years old.

In [33]:
for row in df.itertuples():
    print(row)
    print(row.Index)
    print(f"{row.Name} lives in {row.City}, and is {row.Age} years old.", end='\n\n')

Pandas(Index=0, Name='Alice', Age=25, City='Delhi')
0
Alice lives in Delhi, and is 25 years old.

Pandas(Index=1, Name='Bob', Age=30, City='Mumbai')
1
Bob lives in Mumbai, and is 30 years old.

Pandas(Index=2, Name='Charlie', Age=35, City='Chennai')
2
Charlie lives in Chennai, and is 35 years old.

In [34]:
# Iterating Over Columns

for col in df.columns:
    print(f"Column: {col}")
    print(df[col].values, end='\n\n')

Column: Name
<StringArray>
['Alice', 'Bob', 'Charlie']
Length: 3, dtype: str

Column: Age
[25 30 35]

Column: City
<StringArray>
['Delhi', 'Mumbai', 'Chennai']
Length: 3, dtype: str

# Conditional Example: Add Column with Custom Logic

Based on age column, i want to create a new column that will classify people as 'young' or 'senior'

In [ ]:
categories=[]

for index, row in df.iterrows():
    print(row)
    print(row['Age'])

    if row['Age']<40:
        categories.append('young')
    else:
        categories.append('senior') 

print(categories)

# The Above code will create the data for each n every roe

# now we nned to add the new column in data frame and attach these values

df['Category'] = categories # this is creating the new column and assign the vlues to newly ccrested column

df

Name    Alice
Age        25
City    Delhi
Name: 0, dtype: object
25
Name       Bob
Age         30
City    Mumbai
Name: 1, dtype: object
30
Name    Charlie
Age          35
City    Chennai
Name: 2, dtype: object
35
['young', 'young', 'young']

      Name  Age     City Category
0    Alice   25    Delhi    young
1      Bob   30   Mumbai    young
2  Charlie   35  Chennai    young

# Better Way: Vectorized / Apply

In [6]:
df['Category_vectorized_1'] = df['Age'].apply(lambda age : 'young' if age < 40 else 'senior')


# here apply  acceptts the a funtion in which we cn write the code, so df['Age'] will pass the value to age
df['Category_vectorized_1'].head()

0    young
1    young
2    young
Name: Category_vectorized_1, dtype: str

In [ ]:
categorize_age_lambda = lambda age : 'young' if age < 40 else 'senior'

df['Category_vectorized_2'] = df['Age'].apply(categorize_age_lambda)

df['Category_vectorized_2'].head()

In [7]:
def categorize_age_function(age):
    # if age < 40:
    #     return 'young'
    # else :
    #     return 'senior'
    return 'young' if age < 40 else 'senior'

df['Category_vectorized_3'] = df['Age'].apply(categorize_age_function)

df['Category_vectorized_3'].head()

0    young
1    young
2    young
Name: Category_vectorized_3, dtype: str

In [8]:
df.head

<bound method NDFrame.head of       Name  Age     City Category Category_vectorized_1 Category_vectorized_3
0    Alice   25    Delhi    young                 young                 young
1      Bob   30   Mumbai    young                 young                 young
2  Charlie   35  Chennai    young                 young                 young>

In [ ]:
def check_if_delhi_and_young(row):
    print(row)
    city = row['City']
    age = row['Age']
    if city == 'Delhi':
        if age < 40:
            return True
        else :
            return False
    else:
        return False
    # return 'young' if age < 40 else 'senior'

df['If_young_and_from_delhi'] = df.apply(check_if_delhi_and_young, axis=1)

''' 
In your code:

df['If_young_and_from_delhi'] = df.apply(check_if_delhi_and_young, axis=1)

the axis parameter tells Pandas whether to apply the function row-wise or column-wise.

Syntax
DataFrame.apply(function, axis)
axis = 0 → Apply the function to each column (default)
axis = 1 → Apply the function to each row
Your DataFrame

Suppose your DataFrame is:

import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 45, 30],
    'City': ['Delhi', 'Mumbai', 'Delhi']
})

Output:

Name	Age	City
Alice	25	Delhi
Bob	45	Mumbai
Charlie	30	Delhi
axis=1 (Row-wise)
df.apply(check_if_delhi_and_young, axis=1)

Here Pandas sends one complete row at a time to your function.

First call
row =
Name    Alice
Age        25
City    Delhi
Name: 0

Your function receives:

city = row['City']      # Delhi
age = row['Age']        # 25

Returns

True
Second call
row =
Name      Bob
Age        45
City    Mumbai
Name: 1

Returns

False
Third call
row =
Name     Charlie
Age           30
City      Delhi
Name: 2

Returns

True

Finally Pandas creates

0     True
1    False
2     True
dtype: bool

and stores it in

df['If_young_and_from_delhi']

Final DataFrame

Name	Age	City	If_young_and_from_delhi
Alice	25	Delhi	True
Bob	45	Mumbai	False
Charlie	30	Delhi	True
What happens if you use axis=0?
df.apply(check_if_delhi_and_young, axis=0)

Now Pandas sends one entire column at a time.

First it sends

Name
0      Alice
1        Bob
2    Charlie
Name: Name

Then

Age
0    25
1    45
2    30
Name: Age

Then

City
0     Delhi
1    Mumbai
2     Delhi
Name: City

Your function expects

row['City']

but when Pandas sends the Age column, there is no "City" label in that Series.

So you'll get an error like:

KeyError: 'City'

because your function is written to work with rows, not columns.

Why axis=1 is required here

Your function accesses values from the same record:

city = row['City']
age = row['Age']

A row contains both City and Age, so axis=1 is the correct choice.

Visual summary
axis = 0  (Column-wise)

        ↓
Name
Age
City

Function runs once for each column.


axis = 1 (Row-wise)

→ Alice  25  Delhi
→ Bob    45  Mumbai
→ Charlie 30 Delhi

Function runs once for each row.
Rule to remember
axis=0 → Work down each column (vertical direction).
axis=1 → Work across each row (horizontal direction).

Since your function needs both Age and City from the same person, you use axis=1.



'''

In [9]:
# # axis = 0
# keep column constant and get all rows

# # axis = 1
# keep row constant and get all columns

# Sorting in Pandas

Sorting helps you organize your data for better readability, analysis, and logical operations — whether by index or actual data values.

### Why Sorting Matters

You might want to:

- See top-performing products (e.g., highest sales)

- Order records by name/date

- Prepare data before merging or visualizing

### Two Main Types of Sorting
1. sort_values() → Sort by data values
2. sort_index() → Sort by index (row or column labels)

# 1. sort_values() → Sort by data values

# syntax

```bash
DataFrame.sort_values(by, axis=0, ascending=True, inplace=False, na_position='last')
```

| Argument      | Purpose                                 |
| ------------- | --------------------------------------- |
| `by`          | Column label(s) to sort by              |
| `axis`        | 0 = rows (default), 1 = columns         |
| `ascending`   | True = low to high, False = high to low |
| `inplace`     | True = modify current object            |
| `na_position` | 'first' or 'last' for NaNs              |

In [ ]:
# Example of inplace

class Cal:
    def __init__(self, a):
        self.a = a
    def add(self, b):
        c = self.a + b
        return c
    def inplace_add(self, b):
        self.a = self.a + b
        return self.a
    
c_cal = Cal(10)  # thid method is not updating the value of a by itself , sowe have to perform below operation to update value of a
c_cal.a = c_cal.add(10) # inplace False

# Where below method update the value of a by itself
c_cal.inplace_add(10) # inplace True

In [12]:
import pandas as pd
titanic_dataset_local_url = "titanic.csv"
df = pd.read_csv(titanic_dataset_local_url)

In [ ]:
sort_df=df.sort_values(by='Age')
print(sort_df[['Name','Age']].head(10))#values from first
print(sort_df[['Name','Age']].tail(10)) #values from last

                                         Name   Age
803           Thomas, Master. Assad Alexander  0.42
755                 Hamalainen, Master. Viljo  0.67
644                    Baclini, Miss. Eugenie  0.75
469             Baclini, Miss. Helene Barbara  0.75
78              Caldwell, Master. Alden Gates  0.83
..                                        ...   ...
859                          Razi, Mr. Raihed   NaN
863         Sage, Miss. Dorothy Edith "Dolly"   NaN
868               van Melkebeke, Mr. Philemon   NaN
878                        Laleff, Mr. Kristo   NaN
888  Johnston, Miss. Catherine Helen "Carrie"   NaN

[891 rows x 2 columns]

In [17]:
# to type cast in pandas we use astype
#df['Age']=df['Age'].astype('int64') # thid will give errror since we canot type cast Nan

# we can replace nan with zeros which can be done uso\ing filna(o)

df['Age']=df['Age'].fillna(0).astype('int64')

print(df[['Name','Age']].tail(10))

                                         Name  Age
881                        Markun, Mr. Johann   33
882              Dahlberg, Miss. Gerda Ulrika   22
883             Banfield, Mr. Frederick James   28
884                    Sutehall, Mr. Henry Jr   25
885      Rice, Mrs. William (Margaret Norton)   39
886                     Montvila, Rev. Juozas   27
887              Graham, Miss. Margaret Edith   19
888  Johnston, Miss. Catherine Helen "Carrie"    0
889                     Behr, Mr. Karl Howell   26
890                       Dooley, Mr. Patrick   32

# Example 2: Sort by multiple columns

First sort by Pclass (ascending), then by Fare (descending)

In [18]:
df_sorted = df.sort_values(by=['Pclass', 'Fare'], ascending=[True, False])

df_sorted.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35,0,0,PC 17755,512.3292,B101,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19,3,2,19950,263.0000,C23 C25 C27,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23,3,2,19950,263.0000,C23 C25 C27,S

# 2. sort_index() – Sorting by index

This is useful when you’ve set a meaningful index and want to restore or arrange it.

```bash
DataFrame.sort_index(axis=0, ascending=True, inplace=False)
```

axis=0 → Sort rows

axis=1 → Sort columns

In [19]:
df_sort_2 = df.set_index('PassengerId')
df_sorted_by_index = df_sort_2.sort_index()
df_sorted_by_index.head(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,0,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.0750,NaN,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.0708,NaN,C

# Sorting Columns Alphabetically

In [25]:
df.head()
df.columns

# If we need to arrange the clumn of the data frame we can do it in the below manner

['Ticket', "Parch"]

df[['Ticket', "Parch"]]

#if a dont know the order i want to make it alphabetixcally soerted
sorted(df.columns)

df_column_Sorted=df[sorted(df.columns)]
df_column_Sorted

,Age,Cabin,Embarked,Fare,Name,Parch,PassengerId,Pclass,Sex,SibSp,Survived,Ticket
0,22,NaN,S,7.2500,"Braund, Mr. Owen Harris",0,1,3,male,1,0,A/5 21171
1,38,C85,C,71.2833,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,2,1,female,1,1,PC 17599
2,26,NaN,S,7.9250,"Heikkinen, Miss. Laina",0,3,3,female,0,1,STON/O2. 3101282
3,35,C123,S,53.1000,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,4,1,female,1,1,113803
4,35,NaN,S,8.0500,"Allen, Mr. William Henry",0,5,3,male,0,0,373450
...,...,...,...,...,...,...,...,...,...,...,...,...
886,27,NaN,S,13.0000,"Montvila, Rev. Juozas",0,887,2,male,0,0,211536
887,19,B42,S,30.0000,"Graham, Miss. Margaret Edith",0,888,1,female,0,1,112053
888,0,NaN,S,23.4500,"Johnston, Miss. Catherine Helen ""Carrie""",2,889,3,female,1,0,W./C. 6607
889,26,C148,C,30.0000,"Behr, Mr. Karl Howell",0,890,1,male,0,1,111369
890,32,NaN,Q,7.7500,"Dooley, Mr. Patrick",0,891,3,male,0,0,370376

# Working with Text Data in Pandas

In [26]:
# Lowercase
df['Name'].str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [27]:
# Uppercase
df['Name'].str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: str

In [28]:
# Capitalize
df['Name'].str.capitalize()

0                                Braund, mr. owen harris
1      Cumings, mrs. john bradley (florence briggs th...
2                                 Heikkinen, miss. laina
3           Futrelle, mrs. jacques heath (lily may peel)
4                               Allen, mr. william henry
                             ...
886                                Montvila, rev. juozas
887                         Graham, miss. margaret edith
888             Johnston, miss. catherine helen "carrie"
889                                Behr, mr. karl howell
890                                  Dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [29]:
# String Length
df['Name'].str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64